### ISSUE TITLE
Question: Could you share the background from the screenshot?

### ISSUE THREAD

**Issue by huds0nx** [nextcloud/integration_github#23]
Not an issue but I was just curious as to what the background was in the [screenshot](https://github.com/nextcloud/integration_github/blob/master/img/screenshot1.jpg). It's pretty cool!

**Comment by OSINT-Musings** [comment]
Hiya,

The image was manipulated a little bit (note some of the sharper edges) but I was able to track it back to the European Space Agency per this article.
https://www.theatlantic.com/photo/2016/09/images-from-offworld/499790/#img07
and this one
https://www.newscientist.com/article/mg25033340-800-the-nitrogen-emergency-how-to-fix-our-forgotten-environmental-crisis/

"Though it may appear to be a watercolor painting, this image is a natural-color capture of a plankton bloom in the Barents Sea by the Sentinel-2A satellite. Since plankton contain photosynthetic chlorophyll pigments, these simple organisms play a similar role to terrestrial ‘green’ plants in the photosynthetic process. Although some types of plankton are individually microscopic, the chlorophyll they use for photosynthesis collectively tints the color of the surrounding ocean waters, providing a means of detecting these tiny organisms from space with dedicated sensors, such as Sentinel-2’s multispectral imager."

I've attached the image as it appeared in the screenshot you posted, but you can also pull it from those links.

![Mysterious-and-extraterrestrial-our-Solar-system-04](https://user-images.githubusercontent.com/94326094/200473586-118a589c-7ad1-4971-b8dd-e8a81d51da38.jpg)
